### ISSUE TITLE
Question about the 3D IoU metrics

### ISSUE THREAD

**Issue by Van5SE** [OasisYang/Wild6D#3]
Dear author,
    we noticed that you modified the 3D IoU calculation in your code 
```python
def asymmetric_3d_iou(sRT_1, sRT_2, size_1, size_2):
        noc_cube_1 = get_3d_bbox(size_1, 0)
        bbox_3d_1 = transform_coordinates_3d(noc_cube_1, sRT_1)
        noc_cube_2 = get_3d_bbox(size_2, 0)
        bbox_3d_2 = transform_coordinates_3d(noc_cube_2, sRT_2)
        ## TODO:Need to change to 1 for Wild6D evaluation
        bbox_1_max = np.amax(bbox_3d_1, axis=1)
        bbox_1_min = np.amin(bbox_3d_1, axis=1)
        bbox_2_max = np.amax(bbox_3d_2, axis=1)
        bbox_2_min = np.amin(bbox_3d_2, axis=1)
```

   but reported the metrics calculated by old version code on previous works （such as SPD） in your paper on Table 5 etc.

```python
def asymmetric_3d_iou(sRT_1, sRT_2, size_1, size_2):
        noc_cube_1 = get_3d_bbox(size_1, 0)
        bbox_3d_1 = transform_coordinates_3d(noc_cube_1, sRT_1)
        noc_cube_2 = get_3d_bbox(size_2, 0)
        bbox_3d_2 = transform_coordinates_3d(noc_cube_2, sRT_2)
        bbox_1_max = np.amax(bbox_3d_1, axis=0)
        bbox_1_min = np.amin(bbox_3d_1, axis=0)
        bbox_2_max = np.amax(bbox_3d_2, axis=0)
        bbox_2_min = np.amin(bbox_3d_2, axis=0)
```
  The big difference between two versions of code can lead to very different results.
  I was wondering which version of code did you use to evaluate your model on NOCS and report the results on Table 5 etc. Thank you!

**Comment by OasisYang** [comment]
Sorry for the late reply!!! 
Actually, the original code of computing 3D IOU used in the previous works are inaccurate. We should get the maximum value of x, y and z dimension over eight vertices to describe the size of the 3D box instead of maximum value over x,y,z axis (done in the original version).  To have a fair comparison, we follow the same evaluation implementation (used in most paper before 2022) in our paper to report the results on NOCS.
